// Auto-generated by uploadTestimonialPortraits.ts — do not edit manually

export const SITE_IMAGES = {
  contactHero:
    "https://res.cloudinary.com/ashuudev/image/upload/c_fill,w_1200,h_800,q_auto/v1781277788/posts/seed/3b26a36c40c99e746885ccd04e7e4fb4.jpg",
  portraitFallback: "/avatar.svg",
  portraits: [
      "https://res.cloudinary.com/ashuudev/image/upload/c_fill,g_face,w_800,h_800,q_auto:best,f_auto/v1781295413/site/portraits/person-1.jpg",
      "https://res.cloudinary.com/ashuudev/image/upload/c_fill,g_face,w_800,h_800,q_auto:best,f_auto/v1781295415/site/portraits/person-2.jpg",
      "https://res.cloudinary.com/ashuudev/image/upload/c_fill,g_face,w_800,h_800,q_auto:best,f_auto/v1781295417/site/portraits/person-3.jpg",
      "https://res.cloudinary.com/ashuudev/image/upload/c_fill,g_face,w_800,h_800,q_auto:best,f_auto/v1781295419/site/portraits/person-4.jpg",
      "https://res.cloudinary.com/ashuudev/image/upload/c_fill,g_face,w_800,h_800,q_auto:best,f_auto/v1781295423/site/portraits/person-5.jpg",
      "https://res.cloudinary.com/ashuudev/image/upload/c_fill,g_face,w_800,h_800,q_auto:best,f_auto/v1781295425/site/portraits/person-6.jpg",
      "https://res.cloudinary.com/ashuudev/image/upload/c_fill,g_face,w_800,h_800,q_auto:best,f_auto/v1781295427/site/portraits/person-7.jpg",
      "https://res.cloudinary.com/ashuudev/image/upload/c_fill,g_face,w_800,h_800,q_auto:best,f_auto/v1781295429/site/portraits/person-8.jpg"
  ] as const,
} as const;

export function portraitForIndex(index: number): string {
  return SITE_IMAGES.portraits[index % SITE_IMAGES.portraits.length];
}
