// Auto-generated by migrateImagesToCloudinary.ts — do not edit manually
export const CLOUDINARY_SEED_IMAGES = [
  "https://res.cloudinary.com/ashuudev/image/upload/v1781277788/posts/seed/3b26a36c40c99e746885ccd04e7e4fb4.jpg",
  "https://res.cloudinary.com/ashuudev/image/upload/v1781277790/posts/seed/a261ec64db689c7a6078209d92193911.jpg",
  "https://res.cloudinary.com/ashuudev/image/upload/v1781277791/posts/seed/c08b23ca56d7b56ee6d2bad45ebe499a.jpg",
  "https://res.cloudinary.com/ashuudev/image/upload/v1781277792/posts/seed/e0bfcc59d395014e61edcc0184671ab9.jpg",
  "https://res.cloudinary.com/ashuudev/image/upload/v1781277793/posts/seed/72a2bcb3608d580b0b9ca592f311b8a5.jpg",
  "https://res.cloudinary.com/ashuudev/image/upload/v1781277794/posts/seed/ca9a6d6f2f016e4d40cea87db6cc799d.jpg",
  "https://res.cloudinary.com/ashuudev/image/upload/v1781277795/posts/seed/59753e8db69de6f1eb1072d768bfb07a.jpg",
  "https://res.cloudinary.com/ashuudev/image/upload/v1781277797/posts/seed/5b2ac2b0a73d6a578a0faa18ac817bca.jpg",
  "https://res.cloudinary.com/ashuudev/image/upload/v1781277798/posts/seed/5a03ddff47560e4d652016707500b8fe.jpg",
  "https://res.cloudinary.com/ashuudev/image/upload/v1781277799/posts/seed/3a1aa4b20497c368855c938871222c64.jpg"
] as const;

export function pickSeedImage(index: number): string {
  return CLOUDINARY_SEED_IMAGES[index % CLOUDINARY_SEED_IMAGES.length];
}
