import "dotenv/config";
import crypto from "crypto";
import fs from "fs";
import path from "path";
import mongoose from "mongoose";
import Post from "../models/post";
import { connectDB } from "../db";
import { configureCloudinary, cloudinary } from "../utils/cloudinaryClient";
import { getRedisClient, initRedis } from "../utils/redis";

const REMOTE_HOST_PATTERN = /unsplash\.com|picsum\.photos|placeholder\.com/i;
const POOL_FILE = path.join(__dirname, "cloudinaryImagePool.ts");

function isCloudinaryUrl(url: string): boolean {
  return url.includes("res.cloudinary.com");
}

function isRemoteSeedUrl(url: string): boolean {
  return REMOTE_HOST_PATTERN.test(url);
}

function publicIdForUrl(remoteUrl: string): string {
  const hash = crypto.createHash("md5").update(remoteUrl).digest("hex");
  return `posts/seed/${hash}`;
}

async function uploadRemoteImage(
  remoteUrl: string,
  cache: Map<string, string>
): Promise<string> {
  if (isCloudinaryUrl(remoteUrl)) return remoteUrl;
  if (cache.has(remoteUrl)) return cache.get(remoteUrl)!;

  const publicId = publicIdForUrl(remoteUrl);

  try {
    const existing = await cloudinary.api.resource(publicId, { resource_type: "image" });
    const secureUrl = existing.secure_url as string;
    cache.set(remoteUrl, secureUrl);
    return secureUrl;
  } catch {
    // Resource does not exist yet — upload from remote URL.
  }

  const result = await cloudinary.uploader.upload(remoteUrl, {
    public_id: publicId,
    overwrite: false,
    resource_type: "image",
  });

  cache.set(remoteUrl, result.secure_url);
  return result.secure_url;
}

function writeImagePool(urls: string[]): void {
  const content = `// Auto-generated by migrateImagesToCloudinary.ts — do not edit manually
export const CLOUDINARY_SEED_IMAGES = ${JSON.stringify(urls, null, 2)} as const;

export function pickSeedImage(index: number): string {
  return CLOUDINARY_SEED_IMAGES[index % CLOUDINARY_SEED_IMAGES.length];
}
`;

  fs.writeFileSync(POOL_FILE, content, "utf8");
  console.log(`Wrote ${urls.length} image(s) to ${POOL_FILE}`);
}

async function clearPostListCache(): Promise<void> {
  await initRedis();
  const redis = getRedisClient();
  if (!redis) return;

  const keys: string[] = [];
  const stream = redis.scanStream({ match: "posts:*", count: 100 });
  for await (const batch of stream) {
    keys.push(...(batch as string[]));
  }
  if (keys.length > 0) {
    await redis.del(...keys);
    console.log(`Cleared ${keys.length} cached post key(s)`);
  }
  redis.disconnect();
}

async function migrateImagesToCloudinary(): Promise<void> {
  configureCloudinary();
  await connectDB();

  const posts = await Post.find({
    images: { $elemMatch: { $regex: REMOTE_HOST_PATTERN } },
  });

  console.log(`Found ${posts.length} post(s) with remote seed images`);

  const urlCache = new Map<string, string>();
  let postsUpdated = 0;
  let imagesMigrated = 0;

  for (const post of posts) {
    let changed = false;
    const nextImages: string[] = [];

    for (const imageUrl of post.images) {
      if (isRemoteSeedUrl(imageUrl)) {
        const cloudinaryUrl = await uploadRemoteImage(imageUrl, urlCache);
        nextImages.push(cloudinaryUrl);
        imagesMigrated += 1;
        if (cloudinaryUrl !== imageUrl) changed = true;
      } else {
        nextImages.push(imageUrl);
      }
    }

    if (changed) {
      post.images = nextImages;
      await post.save();
      postsUpdated += 1;
      if (postsUpdated % 25 === 0) {
        console.log(`Updated ${postsUpdated} post(s)...`);
      }
    }
  }

  const poolUrls = [...new Set(urlCache.values())].sort();
  if (poolUrls.length > 0) {
    writeImagePool(poolUrls);
  }

  await clearPostListCache();

  console.log(
    `\nDone. ${postsUpdated} post(s) updated, ${imagesMigrated} image URL(s) migrated, ${urlCache.size} unique upload(s).`
  );
  await mongoose.disconnect();
}

migrateImagesToCloudinary().catch((error) => {
  console.error("Migration failed:", error);
  process.exit(1);
});
