import "dotenv/config";
import mongoose from "mongoose";
import Post from "../models/post";
import PostDetail from "../models/postDetail";
import User from "../models/user";
import { connectDB } from "../db";
import { getRedisClient, initRedis } from "../utils/redis";
import { generateBulkListings, type SeedListing } from "./generateBulkListings";

const IMG = {
  apt1: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
  apt2: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
  house1: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
  house2: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
  condo1: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
  luxury: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
  interior: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&q=80",
  kitchen: "https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?w=800&q=80",
  beach: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&q=80",
  land: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
};

const listings: SeedListing[] = [
  {
    title: "Skyline Studio in Indiranagar",
    price: 850,
    address: "100 Feet Road, Indiranagar",
    city: "Bangalore",
    bedroom: 1,
    bathroom: 1,
    type: "rent",
    property: "apartment",
    latitude: 12.9784,
    longitude: 77.6408,
    images: [IMG.apt1, IMG.interior],
    desc: "<p>Compact studio with balcony views, co-working lounge access, and 24/7 security.</p>",
    size: 650,
    utilities: "included",
    pet: "not_allowed",
    income: "yes",
    school: 1.2,
    bus: 0.3,
    restaurant: 0.1,
  },
  {
    title: "Koramangala 3BHK Family Home",
    price: 2200,
    address: "5th Block, Koramangala",
    city: "Bangalore",
    bedroom: 3,
    bathroom: 2,
    type: "rent",
    property: "apartment",
    latitude: 12.9352,
    longitude: 77.6245,
    images: [IMG.apt2, IMG.kitchen],
    desc: "<p>Spacious 3BHK near cafes and tech parks. Semi-furnished with modular kitchen.</p>",
    size: 1450,
    utilities: "shared",
    pet: "case_by_case",
    income: "yes",
    school: 0.8,
    bus: 0.5,
    restaurant: 0.2,
  },
  {
    title: "Whitefield Villa with Garden",
    price: 450000,
    address: "Prestige Shantiniketan, Whitefield",
    city: "Bangalore",
    bedroom: 4,
    bathroom: 4,
    type: "buy",
    property: "house",
    latitude: 12.9698,
    longitude: 77.7499,
    images: [IMG.house1, IMG.house2],
    desc: "<p>Independent villa with private garden, clubhouse access, and covered parking for two cars.</p>",
    size: 3200,
    utilities: "excluded",
    pet: "allowed",
    income: "no",
    school: 2.0,
    bus: 1.1,
    restaurant: 0.9,
  },
  {
    title: "HSR Layout Premium Condo",
    price: 1850,
    address: "Sector 2, HSR Layout",
    city: "Bangalore",
    bedroom: 2,
    bathroom: 2,
    type: "rent",
    property: "condo",
    latitude: 12.9116,
    longitude: 77.6389,
    images: [IMG.condo1, IMG.interior],
    desc: "<p>Modern condo with gym, rooftop pool, and smart-home lighting throughout.</p>",
    size: 1100,
    utilities: "included",
    pet: "not_allowed",
    income: "yes",
    school: 1.5,
    bus: 0.4,
    restaurant: 0.3,
  },
  {
    title: "MG Road Heritage Apartment",
    price: 320000,
    address: "42 MG Road",
    city: "Bangalore",
    bedroom: 2,
    bathroom: 2,
    type: "buy",
    property: "apartment",
    latitude: 12.9756,
    longitude: 77.6063,
    images: [IMG.luxury, IMG.kitchen],
    desc: "<p>Renovated heritage building unit with high ceilings and city-center walkability.</p>",
    size: 1250,
    utilities: "excluded",
    pet: "case_by_case",
    income: "no",
    school: 0.6,
    bus: 0.2,
    restaurant: 0.1,
  },
  {
    title: "Jayanagar Corner Flat",
    price: 1200,
    address: "4th Block, Jayanagar",
    city: "Bangalore",
    bedroom: 2,
    bathroom: 1,
    type: "rent",
    property: "apartment",
    latitude: 12.9308,
    longitude: 77.5838,
    images: [IMG.apt1],
    desc: "<p>Corner unit with cross ventilation, reserved parking, and proximity to metro.</p>",
    size: 980,
    utilities: "shared",
    pet: "not_allowed",
    income: "no",
    school: 0.4,
    bus: 0.3,
    restaurant: 0.2,
  },
  {
    title: "Electronic City Tech Hub Stay",
    price: 950,
    address: "Neeladri Road, Electronic City",
    city: "Bangalore",
    bedroom: 1,
    bathroom: 1,
    type: "rent",
    property: "apartment",
    latitude: 12.8456,
    longitude: 77.6603,
    images: [IMG.apt2],
    desc: "<p>Ideal for IT professionals. Furnished 1BHK with high-speed fiber internet.</p>",
    size: 720,
    utilities: "included",
    pet: "not_allowed",
    income: "yes",
    school: 3.0,
    bus: 0.6,
    restaurant: 0.8,
  },
  {
    title: "Nandi Hills Weekend Retreat",
    price: 180,
    address: "Nandi Hills Road",
    city: "Bangalore",
    bedroom: 2,
    bathroom: 1,
    type: "vacation",
    property: "house",
    latitude: 13.3702,
    longitude: 77.6835,
    images: [IMG.house2, IMG.beach],
    desc: "<p>Hill-view cottage perfect for weekend getaways. Fireplace and outdoor deck.</p>",
    size: 1400,
    utilities: "included",
    pet: "allowed",
    income: "no",
    school: 8.0,
    bus: 5.0,
    restaurant: 2.5,
  },
  {
    title: "Bandra Sea-Facing Penthouse",
    price: 8500,
    address: "Linking Road, Bandra West",
    city: "Mumbai",
    bedroom: 3,
    bathroom: 3,
    type: "rent",
    property: "condo",
    latitude: 19.0596,
    longitude: 72.8295,
    images: [IMG.luxury, IMG.condo1],
    desc: "<p>Luxury penthouse with Arabian Sea views, concierge, and private elevator access.</p>",
    size: 2100,
    utilities: "included",
    pet: "case_by_case",
    income: "yes",
    school: 1.0,
    bus: 0.2,
    restaurant: 0.1,
  },
  {
    title: "Andheri East Compact 2BHK",
    price: 2800,
    address: "Marol, Andheri East",
    city: "Mumbai",
    bedroom: 2,
    bathroom: 2,
    type: "rent",
    property: "apartment",
    latitude: 19.1136,
    longitude: 72.8697,
    images: [IMG.apt2, IMG.interior],
    desc: "<p>Well-connected 2BHK near metro and airport. Recently repainted and move-in ready.</p>",
    size: 900,
    utilities: "shared",
    pet: "not_allowed",
    income: "yes",
    school: 1.8,
    bus: 0.4,
    restaurant: 0.3,
  },
  {
    title: "Powai Lakeview Residence",
    price: 1250000,
    address: "Hiranandani Gardens, Powai",
    city: "Mumbai",
    bedroom: 3,
    bathroom: 3,
    type: "buy",
    property: "apartment",
    latitude: 19.1176,
    longitude: 72.906,
    images: [IMG.apt1, IMG.kitchen],
    desc: "<p>Iconic Powai address with lake views, landscaped gardens, and top-tier schools nearby.</p>",
    size: 1650,
    utilities: "excluded",
    pet: "allowed",
    income: "no",
    school: 0.5,
    bus: 0.6,
    restaurant: 0.4,
  },
  {
    title: "Juhu Beach Vacation Bungalow",
    price: 350,
    address: "Juhu Tara Road",
    city: "Mumbai",
    bedroom: 3,
    bathroom: 2,
    type: "vacation",
    property: "house",
    latitude: 19.107,
    longitude: 72.8263,
    images: [IMG.beach, IMG.house1],
    desc: "<p>Steps from Juhu Beach. Ideal for family holidays with full kitchen and patio.</p>",
    size: 1800,
    utilities: "included",
    pet: "allowed",
    income: "no",
    school: 2.2,
    bus: 0.7,
    restaurant: 0.2,
  },
  {
    title: "Lower Parel High-Rise Studio",
    price: 3200,
    address: "Senapati Bapat Marg, Lower Parel",
    city: "Mumbai",
    bedroom: 1,
    bathroom: 1,
    type: "rent",
    property: "apartment",
    latitude: 19.005,
    longitude: 72.83,
    images: [IMG.apt1],
    desc: "<p>Urban studio in the financial district with floor-to-ceiling windows.</p>",
    size: 580,
    utilities: "included",
    pet: "not_allowed",
    income: "yes",
    school: 1.4,
    bus: 0.1,
    restaurant: 0.1,
  },
  {
    title: "Gurugram Golf Course Road Villa",
    price: 2100000,
    address: "Sector 53, Golf Course Road",
    city: "Gurugram",
    bedroom: 5,
    bathroom: 5,
    type: "buy",
    property: "house",
    latitude: 28.4595,
    longitude: 77.0266,
    images: [IMG.house1, IMG.luxury],
    desc: "<p>Ultra-luxury villa with home theater, staff quarters, and triple-height foyer.</p>",
    size: 5200,
    utilities: "excluded",
    pet: "allowed",
    income: "no",
    school: 1.2,
    bus: 1.5,
    restaurant: 0.8,
  },
  {
    title: "DLF Phase 3 Modern Flat",
    price: 2400,
    address: "DLF Phase 3, U Block",
    city: "Gurugram",
    bedroom: 2,
    bathroom: 2,
    type: "rent",
    property: "apartment",
    latitude: 28.4929,
    longitude: 77.1025,
    images: [IMG.apt2, IMG.kitchen],
    desc: "<p>Secure gated community flat with power backup and children's play area.</p>",
    size: 1150,
    utilities: "shared",
    pet: "case_by_case",
    income: "yes",
    school: 0.9,
    bus: 0.5,
    restaurant: 0.4,
  },
  {
    title: "Cyber City Furnished 1BHK",
    price: 1100,
    address: "DLF Cyber City",
    city: "Gurugram",
    bedroom: 1,
    bathroom: 1,
    type: "rent",
    property: "apartment",
    latitude: 28.495,
    longitude: 77.088,
    images: [IMG.interior],
    desc: "<p>Walk to work from this fully furnished unit with weekly housekeeping.</p>",
    size: 680,
    utilities: "included",
    pet: "not_allowed",
    income: "yes",
    school: 2.5,
    bus: 0.2,
    restaurant: 0.1,
  },
  {
    title: "Sohna Road Plot for Development",
    price: 380000,
    address: "Sector 33, Sohna Road",
    city: "Gurugram",
    bedroom: 0,
    bathroom: 0,
    type: "buy",
    property: "land",
    latitude: 28.4031,
    longitude: 77.0456,
    images: [IMG.land],
    desc: "<p>500 sq yd residential plot with clear title and road frontage on Sohna Road.</p>",
    size: 4500,
    utilities: "excluded",
    pet: "allowed",
    income: "no",
    school: 4.0,
    bus: 2.0,
    restaurant: 3.0,
  },
  {
    title: "Hauz Khas Village Loft",
    price: 1650,
    address: "Hauz Khas Village",
    city: "Delhi",
    bedroom: 2,
    bathroom: 1,
    type: "rent",
    property: "apartment",
    latitude: 28.5535,
    longitude: 77.194,
    images: [IMG.interior, IMG.apt1],
    desc: "<p>Artistic loft in Delhi's cultural hub. Exposed brick, skylights, and cafe district access.</p>",
    size: 920,
    utilities: "shared",
    pet: "case_by_case",
    income: "no",
    school: 1.0,
    bus: 0.3,
    restaurant: 0.05,
  },
  {
    title: "Dwarka Sector 21 Family Apartment",
    price: 2800,
    address: "Sector 21, Dwarka",
    city: "Delhi",
    bedroom: 3,
    bathroom: 2,
    type: "rent",
    property: "apartment",
    latitude: 28.5522,
    longitude: 77.0439,
    images: [IMG.apt2],
    desc: "<p>Metro-connected 3BHK with society clubhouse, tennis court, and ample parking.</p>",
    size: 1380,
    utilities: "shared",
    pet: "not_allowed",
    income: "yes",
    school: 0.7,
    bus: 0.2,
    restaurant: 0.5,
  },
  {
    title: "Greater Kailash Bungalow",
    price: 1850000,
    address: "M Block, Greater Kailash II",
    city: "Delhi",
    bedroom: 4,
    bathroom: 3,
    type: "buy",
    property: "house",
    latitude: 28.5355,
    longitude: 77.241,
    images: [IMG.house2, IMG.house1],
    desc: "<p>South Delhi bungalow with lawn, servant room, and two-car garage.</p>",
    size: 3600,
    utilities: "excluded",
    pet: "allowed",
    income: "no",
    school: 0.5,
    bus: 0.4,
    restaurant: 0.3,
  },
  {
    title: "Connaught Place Executive Suite",
    price: 220,
    address: "Block A, Connaught Place",
    city: "Delhi",
    bedroom: 1,
    bathroom: 1,
    type: "vacation",
    property: "condo",
    latitude: 28.6315,
    longitude: 77.2167,
    images: [IMG.condo1, IMG.luxury],
    desc: "<p>Short-stay executive suite in central Delhi. Housekeeping and room service available.</p>",
    size: 750,
    utilities: "included",
    pet: "not_allowed",
    income: "no",
    school: 1.5,
    bus: 0.1,
    restaurant: 0.05,
  },
  {
    title: "Jubilee Hills Luxury Condo",
    price: 3200,
    address: "Road No. 36, Jubilee Hills",
    city: "Hyderabad",
    bedroom: 3,
    bathroom: 3,
    type: "rent",
    property: "condo",
    latitude: 17.4326,
    longitude: 78.4071,
    images: [IMG.luxury, IMG.condo1],
    desc: "<p>Premium condo with infinity pool, spa, and panoramic city views.</p>",
    size: 1900,
    utilities: "included",
    pet: "case_by_case",
    income: "yes",
    school: 1.1,
    bus: 0.6,
    restaurant: 0.4,
  },
  {
    title: "Gachibowli IT Corridor Flat",
    price: 1350,
    address: "Nanakramguda, Gachibowli",
    city: "Hyderabad",
    bedroom: 2,
    bathroom: 2,
    type: "rent",
    property: "apartment",
    latitude: 17.4401,
    longitude: 78.3489,
    images: [IMG.apt2],
    desc: "<p>Modern 2BHK near major tech campuses. Gated community with 24/7 water supply.</p>",
    size: 1050,
    utilities: "shared",
    pet: "not_allowed",
    income: "yes",
    school: 2.0,
    bus: 0.5,
    restaurant: 0.6,
  },
  {
    title: "Banjara Hills Designer Home",
    price: 980000,
    address: "Road No. 12, Banjara Hills",
    city: "Hyderabad",
    bedroom: 4,
    bathroom: 4,
    type: "buy",
    property: "house",
    latitude: 17.4156,
    longitude: 78.4347,
    images: [IMG.house1, IMG.interior],
    desc: "<p>Architect-designed home with indoor courtyard, home office, and solar panels.</p>",
    size: 3400,
    utilities: "excluded",
    pet: "allowed",
    income: "no",
    school: 0.8,
    bus: 0.7,
    restaurant: 0.3,
  },
  {
    title: "Manhattan Midtown Loft",
    price: 4200,
    address: "450 West 42nd Street",
    city: "New York",
    bedroom: 2,
    bathroom: 1,
    type: "rent",
    property: "apartment",
    latitude: 40.758,
    longitude: -73.9855,
    images: [IMG.apt1, IMG.interior],
    desc: "<p>Industrial-chic loft near Times Square. Exposed beams and chef's kitchen.</p>",
    size: 1100,
    utilities: "excluded",
    pet: "case_by_case",
    income: "yes",
    school: 0.6,
    bus: 0.1,
    restaurant: 0.05,
  },
  {
    title: "Brooklyn Brownstone",
    price: 1250000,
    address: "124 Prospect Heights",
    city: "New York",
    bedroom: 4,
    bathroom: 2,
    type: "buy",
    property: "house",
    latitude: 40.6754,
    longitude: -73.9719,
    images: [IMG.house2, IMG.kitchen],
    desc: "<p>Classic brownstone with original moldings, garden level, and renovated roof deck.</p>",
    size: 2800,
    utilities: "excluded",
    pet: "allowed",
    income: "no",
    school: 0.4,
    bus: 0.2,
    restaurant: 0.1,
  },
  {
    title: "Miami Beach Oceanfront Condo",
    price: 275,
    address: "1200 Ocean Drive",
    city: "Miami",
    bedroom: 2,
    bathroom: 2,
    type: "vacation",
    property: "condo",
    latitude: 25.7825,
    longitude: -80.1348,
    images: [IMG.beach, IMG.condo1],
    desc: "<p>Beachfront condo with direct ocean access. Perfect for winter escapes.</p>",
    size: 950,
    utilities: "included",
    pet: "not_allowed",
    income: "no",
    school: 3.0,
    bus: 0.8,
    restaurant: 0.1,
  },
  {
    title: "Austin Downtown High-Rise",
    price: 3100,
    address: "200 Congress Avenue",
    city: "Austin",
    bedroom: 2,
    bathroom: 2,
    type: "rent",
    property: "apartment",
    latitude: 30.2648,
    longitude: -97.7431,
    images: [IMG.apt2, IMG.luxury],
    desc: "<p>Downtown living with rooftop lounge, co-working space, and Lady Bird Lake views.</p>",
    size: 1020,
    utilities: "included",
    pet: "allowed",
    income: "yes",
    school: 1.2,
    bus: 0.2,
    restaurant: 0.1,
  },
  {
    title: "Seattle Capitol Hill Townhouse",
    price: 875000,
    address: "1420 E Pine Street",
    city: "Seattle",
    bedroom: 3,
    bathroom: 2,
    type: "buy",
    property: "house",
    latitude: 47.6159,
    longitude: -122.326,
    images: [IMG.house1, IMG.interior],
    desc: "<p>Three-level townhouse with rooftop terrace and EV charging in the garage.</p>",
    size: 1850,
    utilities: "excluded",
    pet: "allowed",
    income: "no",
    school: 0.5,
    bus: 0.3,
    restaurant: 0.2,
  },
  {
    title: "San Francisco SOMA Loft",
    price: 4800,
    address: "880 Folsom Street",
    city: "San Francisco",
    bedroom: 1,
    bathroom: 1,
    type: "rent",
    property: "apartment",
    latitude: 37.7815,
    longitude: -122.404,
    images: [IMG.interior, IMG.apt1],
    desc: "<p>Open-plan loft in SOMA with floor-to-ceiling windows and in-unit laundry.</p>",
    size: 870,
    utilities: "excluded",
    pet: "not_allowed",
    income: "yes",
    school: 0.9,
    bus: 0.1,
    restaurant: 0.1,
  },
  {
    title: "Chicago Lincoln Park Duplex",
    price: 2650,
    address: "2100 N Halsted Street",
    city: "Chicago",
    bedroom: 3,
    bathroom: 2,
    type: "rent",
    property: "condo",
    latitude: 41.9214,
    longitude: -87.6494,
    images: [IMG.condo1, IMG.kitchen],
    desc: "<p>Duplex condo steps from Lincoln Park Zoo. Fireplace, deck, and in-building storage.</p>",
    size: 1550,
    utilities: "shared",
    pet: "case_by_case",
    income: "yes",
    school: 0.3,
    bus: 0.2,
    restaurant: 0.15,
  },
];

async function clearPostListCache(): Promise<void> {
  await initRedis();
  const redis = getRedisClient();
  if (!redis) return;

  const keys: string[] = [];
  const stream = redis.scanStream({ match: "posts:list:*", count: 100 });
  for await (const batch of stream) {
    keys.push(...(batch as string[]));
  }
  if (keys.length > 0) {
    await redis.del(...keys);
    console.log(`Cleared ${keys.length} cached post list key(s)`);
  }
  redis.disconnect();
}

async function seedPosts() {
  await connectDB();

  const bulkCount = Number(process.argv[2]) || 0;
  const batchOffset = Number(process.argv[3]) || 1000;
  const toSeed: SeedListing[] =
    bulkCount > 0 ? generateBulkListings(bulkCount, batchOffset) : listings;

  const ownerId = process.env.SEED_OWNER_ID;
  const owner = ownerId
    ? await User.findById(ownerId)
    : await User.findOne({ accountType: "owner" });

  if (!owner) {
    console.error("No owner user found. Set SEED_OWNER_ID in .env or create an owner account.");
    process.exit(1);
  }

  console.log(`Seeding ${toSeed.length} listings for owner: ${owner.username}`);

  let created = 0;
  let skipped = 0;
  for (const listing of toSeed) {
    const existing = await Post.findOne({ title: listing.title, city: listing.city });
    if (existing) {
      skipped += 1;
      continue;
    }

    const post = await Post.create({
      userId: owner._id,
      title: listing.title,
      price: listing.price,
      address: listing.address,
      city: listing.city,
      bedroom: listing.bedroom,
      bathroom: listing.bathroom,
      type: listing.type,
      property: listing.property,
      latitude: listing.latitude,
      longitude: listing.longitude,
      images: listing.images,
    });

    await PostDetail.create({
      desc: listing.desc,
      utilities: listing.utilities,
      pet: listing.pet,
      income: listing.income,
      size: listing.size,
      school: listing.school,
      bus: listing.bus,
      restaurant: listing.restaurant,
      postId: post._id,
    });

    created += 1;
    if (created % 25 === 0 || created === toSeed.length) {
      console.log(`Progress: ${created} created...`);
    }
  }

  await clearPostListCache();

  console.log(`\nDone. ${created} new listing(s) added, ${skipped} skipped.`);
  await mongoose.disconnect();
}

seedPosts().catch((error) => {
  console.error("Seed failed:", error);
  process.exit(1);
});
