import "dotenv/config";
import fs from "fs";
import path from "path";
import { configureCloudinary, cloudinary } from "../utils/cloudinaryClient";

/**
 * High-resolution portrait sources (1200×1200, face-cropped).
 * Uploaded once to Cloudinary — the site only serves from Cloudinary at runtime.
 */
const PORTRAIT_SOURCES = [
  "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=1200&h=1200&fit=crop&crop=faces&q=90",
  "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&h=1200&fit=crop&crop=faces&q=90",
  "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=1200&h=1200&fit=crop&crop=faces&q=90",
  "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=1200&h=1200&fit=crop&crop=faces&q=90",
  "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=1200&h=1200&fit=crop&crop=faces&q=90",
  "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=1200&h=1200&fit=crop&crop=faces&q=90",
  "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=1200&h=1200&fit=crop&crop=faces&q=90",
  "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=1200&h=1200&fit=crop&crop=faces&q=90",
] as const;

const CLIENT_SITE_IMAGES = path.join(
  __dirname,
  "../../client/src/lib/siteImages.ts"
);

/** 800px square @ high quality — sharp on retina for ~320px display cards. */
const PORTRAIT_TRANSFORM = "c_fill,g_face,w_800,h_800,q_auto:best,f_auto";

async function uploadPortrait(remoteUrl: string, publicId: string): Promise<string> {
  const result = await cloudinary.uploader.upload(remoteUrl, {
    public_id: publicId,
    overwrite: true,
    invalidate: true,
    resource_type: "image",
  });

  return result.secure_url;
}

function portraitDeliveryUrl(secureUrl: string): string {
  return secureUrl.replace("/upload/", `/upload/${PORTRAIT_TRANSFORM}/`);
}

async function main(): Promise<void> {
  configureCloudinary();

  const uploaded: string[] = [];

  for (let i = 0; i < PORTRAIT_SOURCES.length; i++) {
    const source = PORTRAIT_SOURCES[i];
    const publicId = `site/portraits/person-${i + 1}`;
    console.log(`Uploading portrait ${i + 1}/${PORTRAIT_SOURCES.length}…`);
    const secureUrl = await uploadPortrait(source, publicId);
    uploaded.push(portraitDeliveryUrl(secureUrl));
    console.log(`  → ${uploaded[uploaded.length - 1]}`);
  }

  const contactHero =
    "https://res.cloudinary.com/ashuudev/image/upload/c_fill,w_1200,h_800,q_auto/v1781277788/posts/seed/3b26a36c40c99e746885ccd04e7e4fb4.jpg";

  const content = `// Auto-generated by uploadTestimonialPortraits.ts — do not edit manually

export const SITE_IMAGES = {
  contactHero:
    "${contactHero}",
  portraitFallback: "/avatar.svg",
  portraits: ${JSON.stringify(uploaded, null, 4).replace(/\n/g, "\n  ")} as const,
} as const;

export function portraitForIndex(index: number): string {
  return SITE_IMAGES.portraits[index % SITE_IMAGES.portraits.length];
}
`;

  fs.writeFileSync(CLIENT_SITE_IMAGES, content, "utf8");
  console.log(`\nWrote ${CLIENT_SITE_IMAGES}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
